---
kind: Service
apiVersion: v1
metadata:
  name: jenkins-pub
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
      nodePort: 8081
  selector:
    app: jenkins
